### ISSUE TITLE
which tablet is recommended for use with AgOpenGPS as the tractor terminal?

### ISSUE THREAD

**Issue by svenn71** [farmerbriantee/AgOpenGPS#10]
Never bought a windows tablet for use with c# programs. Need some pointers to hardware where AOG will run.

**Comment by farmerbriantee** [comment]
it will run on most tablets but i use an acer switch 12. you need to be able to use the usb and also charge it but many tablets can't do that.

**Comment by svenn71** [comment]
Got myself an ODYS 8 inch windows 10 tablet for EUR 69 and one of these USB-otg-charge-hubs from dx for EUR 2. Works. Build quality of the USB-otg is really crap, but I wanted a low-cost low-risk start with AOG.
