### ISSUE TITLE
Can't open a saved field

### ISSUE THREAD

**Issue by JeremyLebon** [farmerbriantee/AgOpenGPS#151]
Dear,

When reopening a saved field. I get error below.
![image](https://user-images.githubusercontent.com/11572615/77862277-b7683f00-721a-11ea-81e9-fe624fec3c9f.png)

There fields saved in the directory documents > AgOpenGps > Fields.

Thanks for the feedback

Jeremy

**Comment by richardklasens** [comment]
Hi Jeremy. There is probably an old (corrupted) field inside your fields folder. Leave only the real fields and remove the testing ones. 

If you have more difficulties, please go the forum on Discourse and search or post a question there.

**Comment by richardklasens** [comment]
http://agopengps.discourse.group
