### ISSUE TITLE
FormABDraw unhandled exception

### ISSUE THREAD

**Issue by GaetanVigner** [farmerbriantee/AgOpenGPS#162]
In FormABDraw -> DrawSections line 764
Index out of range exception
Happens every time I click on/off in FormABDraw 
```
for (int i = 0; i < cnt; i += step)
{
    GL.Vertex3(triList[i].easting, triList[i].northing, 0); i++;
    GL.Vertex3(triList[i].easting, triList[i].northing, 0); i++; //out of range here

    //too small to mipmap it
    if (cnt - i <= (mipmap + 2))
        step = 0;
}
```

**Comment by mirh** [comment]
Fixed in https://github.com/farmerbriantee/AgOpenGPS/commit/ec0ef129bf217f2b0cdade6a9abcd06cbe6f83a0#diff-2179be5bf03dd7cf467e32ce9defc14ba00e2f588bfff388222e9e1991cb0f82 maybe?
