### ISSUE TITLE
ArduinoCode is missing in the master branch

### ISSUE THREAD

**Issue by hagre** [farmerbriantee/AgOpenGPS#165]
The folder ArduinoCode is missing in the master branch.

**Comment by richardklasens** [comment]
You can find it in the release section.

**Comment by hagre** [comment]
Thank you for the quick replay.  Would it be possible (does it make sence) to present the actual/not released Arduino Folder in a seperate Repository? So everyone could make pull requests and try to participate/improve the software.

**Comment by richardklasens** [comment]
Will be added
