### ISSUE TITLE
Is it wrong calculating angular velocity in CABLine.cs ?

### ISSUE THREAD

**Issue by luckydaxiang** [farmerbriantee/AgOpenGPS#170]
The formula  for angular velocity is ω = v / r .
In  CABLine.cs line 587, I think it should be :  `angVel = 0.277777 * mf.pn.speed * (Math.Tan(glm.toRadians(steerAngleAB))) / mf.vehicle.wheelbase;`
![image](https://user-images.githubusercontent.com/16378215/84883762-82ee7b80-b0c3-11ea-813c-ef71cdf0c876.png)
Can you explain to me ? Thank you .

**Comment by yuyongji1987** [comment]
I have the same question. Did you get the answer?

**Comment by mirh** [comment]
https://physics.stackexchange.com/questions/112301/calculating-the-rate-at-which-a-car-turns
Mhh.. Indeed something smells off. Perhaps there was some mix up with the uniform circular motion formula?

**Comment by farmerbriantee** [comment]
> The formula for angular velocity is ω = v / r .
> In CABLine.cs line 587, I think it should be : `angVel = 0.277777 * mf.pn.speed * (Math.Tan(glm.toRadians(steerAngleAB))) / mf.vehicle.wheelbase;`
> ![image](https://user-images.githubusercontent.com/16378215/84883762-82ee7b80-b0c3-11ea-813c-ef71cdf0c876.png)
> Can you explain to me ? Thank you .

Sure can, angvel isn't actually used and adding pi several years ago made it easy for setting the value against a slider - none of which is used anymore anyway.
