### ISSUE TITLE
Can't switch back to Simulator mode after setup

### ISSUE THREAD

**Issue by mirh** [farmerbriantee/AgOpenGPS#177]
I think the steps to reproduce are:
* configure your GPS receiver and connect it to AOG
* close AOG
* start it again and wait for precision to get good enough the "I'm lost" marker is no more
* get back to the "Serial Ports" window and disconnect it
* switch on simulator and click to restart

It's like the last two steps never happened.

**Comment by richardklasens** [comment]
You have to disconnect the USB cable, otherwise it will reconnect to the latest chosen serialport

**Comment by mirh** [comment]
I get that the connect/disconnect buttons may only be temporary to the local session.. But if I enable the simulator and I restart the program to get that, I am expecting that.

**Comment by richardklasens** [comment]
This is solved by using AgIO. Close it, turn on sim. As soon as agIO is running and is sending position data, sim is turned off again
