### ISSUE TITLE
Same KML is loaded with different sizes

### ISSUE THREAD

**Issue by mirh** [farmerbriantee/AgOpenGPS#181]
As also reported [here](https://agopengps.discourse.group/t/wrong-file-area-size-of-google-earth-kml-imported-boundary/1726).. But I have a [testcase](https://github.com/farmerbriantee/AgOpenGPS/files/5526806/Fields.zip) on my side. 

Basically, if you open the KML on a fresh AOG instance with the first field loaded, it's the right size of about 1 hectare and half. 
If you open the same thing while you have the second field in memory, it's something like *77*.

**Comment by mirh** [comment]
I'm not even able to open the old files anymore. 
The .kml throws a "Boundary Lines File Corrupt - But Field Is Loaded" error. 
And one of the two fields doesn't show anything.

**Comment by richardklasens** [comment]
You should be able to open fields from 4.3

**Comment by mirh** [comment]
One opens, the other doesn't. 
They are attached in the second link above, if it wasn't clear.

**Comment by richardklasens** [comment]
Open kml or open field txt from 4.3?
