### ISSUE TITLE
antennaoffset posivite or negative?

### ISSUE THREAD

**Issue by yuyongji1987** [farmerbriantee/AgOpenGPS#184]
![image](https://user-images.githubusercontent.com/6849607/101460298-61849300-3974-11eb-9d10-a3d26de950d3.png)
hello,
(x,y) is the antenna position, and (x1,y1) is the tractor position. In my opinion, when the antenna is on the left, the antenna offset is positive, is it right?

**Comment by tomischmid** [comment]
Ja

**Comment by yuyongji1987** [comment]
> Ja

thank you.
