### ISSUE TITLE
Datei nicht installierbar

### ISSUE THREAD

**Issue by Rammer12** [farmerbriantee/AgOpenGPS#185]
Grüße euch!

Ich bin neu hier und habe ein großes Problem:
Und zwar, kann ich auf meinem Tablet (Win10) keine msi datei installieren. Ich bekomme folgende Fehlermeldung

"Sie müssen eine App für diese Aufgabe installieren. - Möchten sie im store danach suchen?"

Egal ob ich ja oder nein klicke folgt dann die nächste Meldung: 

"Dieses Installationspaket konnte nicht geöffnet werden. Stellen Sie sicher, dass das Paket existiert und dass sie darauf zugreifen können. Oder lassen sie den Hersteller der Anwendung überprüfen, ob es sich um ein gültiges Windows Installer-Paket handelt."

Das eigenartige daran ist auf dem PC läuft das Programm ohne Probleme...

Ich bedanke mich jetzt schon für eure Ratschläge und hoffe das irgendwer eine schnelle Lösung parat hat da ich dieses Programm dringend benötige.

ein anderer Lösungsweg für mich wäre wenn es die Datei auch als .exe gäbe aber da kenn ich mich zu wenig aus ob das so leicht
realisierbar ist.

besten dank und viele Grüße!

**Comment by tomischmid** [comment]
Stell die Frage besser in der Telegram Gruppe da wird dir sicher schnell geholfen: https://t.me/AGOpenGPSGerman
