### ISSUE TITLE
AutoSteerCalculation Thread

### ISSUE THREAD

**Issue by PeterHaas1983** [farmerbriantee/AgOpenGPS#187]
I've just read a little bit into the sourceCode.
And I found out the AutoSteer Calculation is done in a windows forms thread.
Is this correct.

In my opinion, this is a very critically operation, and it should not be done in the GUI task.

Better would to encapsulate this operation in a higher prio task like
System.Timers.Timer
or
System.Threading.Thread

**Comment by richardklasens** [comment]
We are using tasks now for different purposes
