### ISSUE TITLE
windows defender detect trojan  v4.3.10

### ISSUE THREAD

**Issue by shup88** [farmerbriantee/AgOpenGPS#191]
Windows defender is detecting a Trojan on the v4.3.10 MSI download.

**Comment by ogry** [comment]
Exactly the same 

Trojan:Win32/Ludicrouz.I

**Comment by farmerbriantee** [comment]
A problem with Windows defender, Not AgOpenGPS

**Comment by mirh** [comment]
The false positive is no more AFAICT, though a digital signature would go a long way into avoiding such issues.
