### ISSUE TITLE
Add second %coverage setting for boundary overlap?

### ISSUE THREAD

**Issue by GertSchouterden** [farmerbriantee/AgOpenGPS#201]
Would it be possible to add a second % Coverage setting that defines the needed overlap with the boundary before a section switches off.
Currently this seems to be fixed of 0/1% resulting in unneeded turning off of the outside section when slight deviation of the path occurs or when you are working on crooked headlands.

**Comment by farmerbriantee** [comment]
You can just use manual sections when going around the border. Current version is quite difficult to add percentage boundary overlap
