### ISSUE TITLE
discourse group cannot be found

### ISSUE THREAD

**Issue by svenn71** [farmerbriantee/AgOpenGPS#217]
when clicking on the link to the discussion group, discourse says that the group does not exist there.
Has something bad happened?

**Comment by richardklasens** [comment]
We switched to a self hosted solution about a month ago. It was posted on the old forum and all telegram groups. 

Please use your credentials from the old discourse forum on our new link

https://discourse.agopengps.com

**Comment by mirh** [comment]
Why in the heaven is the forum set to private?

**Comment by FarmerKevin** [comment]
Yes I could get on a few days ago, but not now.On Sep 16, 2021 10:03 AM, svenn71 ***@***.***> wrote:
when clicking on the link to the discussion group, discourse says that the group does not exist there.
Has something bad happened?

**Comment by mirh** [comment]
Fixed in #218 I guess, but there's still no explanation on why threads aren't public anymore.

**Comment by richardklasens** [comment]
> Fixed in #218 I guess, but there's still no explanation on why threads aren't public anymore.

We had some problems with our old discourse plan, which forced us to turn this function on. It’s public again now. 

Sorry for the late reply

**Comment by mirh** [comment]
Thank you!
