### ISSUE TITLE
Antenna Offset and roll - vice versa

### ISSUE THREAD

**Issue by aortner** [farmerbriantee/AgOpenGPS#24]
antenna offset and roll are vice versa now.

**Comment by WTalen** [comment]
As to say looking at back of tractor, tilting the right side up is negative? And an antenna on the right side of the tractor would be negative now?
![roll](https://user-images.githubusercontent.com/30629955/38455215-78cd8bb4-3a4b-11e8-9db3-c895d82fcbc0.png)

**Comment by farmerbriantee** [comment]
I never changed anything. Roll polarity is the same for a long time now.

**Comment by aortner** [comment]
Roll - maybe my mistake in my setup of my gps..

but antenna offset is the wrong way - if i rerun agopengps with 1 m - its to the right - but it should be to the left...

![antenna](https://user-images.githubusercontent.com/23136635/38464340-8ab9e1b2-3b0c-11e8-9943-31821ba96407.png)

**Comment by farmerbriantee** [comment]
If its in the wrong plaMAce, go the other direction with the setting. I know that's really obvious, but I'll try to standardize this stuff to follow the plane standard

**Comment by aortner** [comment]
yes i did change setting the other direction..
-took my some time to find out was was wrong...
