### ISSUE TITLE
Can not create account on Discourse.agopengps

### ISSUE THREAD

**Issue by K2AAE** [farmerbriantee/AgOpenGPS#247]
Tried to create an account but the system will not finish checking the user name. Just trying to post were you can get RTK GPS chip sets that put the crap being sold to shame, Quad GNSS with L1/L2 dual antenna input

**Comment by richardklasens** [comment]
Hmm what username did you tried? I will check

**Comment by richardklasens** [comment]
Can you try this link?

https://discourse.agopengps.com/invites/fBEdVFA3u3

**Comment by richardklasens** [comment]
Closed due to no response :)
