### ISSUE TITLE
Working with boundarys and sections

### ISSUE THREAD

**Issue by aortner** [farmerbriantee/AgOpenGPS#25]
Working with boundarys and sections needs a setting when a section is switching off!

Now when as sections hits boundray its off..

a) sections is only off when its completly outside
b) you have a setting (sections is off when x % outside of boundary)

![bach](https://user-images.githubusercontent.com/23136635/38457273-5c24857e-3a8e-11e8-871a-3e7b4b94fe0c.png)

**Comment by farmerbriantee** [comment]
Can not be done with existing code. Can't measure a distance outside of boundary, only know if the point is in, or out. You can put the section in manual if you want to apply outside the boundary.
