### ISSUE TITLE
AutoSteerPCBv2_Original - ADS1115 board from Adafruit - pinout changed as of June 22, 2022

### ISSUE THREAD

**Issue by BenjiWiebe** [farmerbriantee/AgOpenGPS#274]
In Support/Misc/PCB/AutoSteerPCBv2_Original.zip, the parts list spreadsheet lists Adafruit as an acceptable place to get the ADC (ADS1115) board.

As of June 22, 2022, Adafruit now sells the ADS1115 board in a two-row pin configuration instead of one row. Adafruit should probably be taken out of the spreadsheet and a note would also be helpful to make sure you buy the single row version.

**Comment by richardklasens** [comment]
We’ve added an SMD version of the ADS1115 to the newest boards, so no need for a new footprint. The old one is still there for backwards compatibility.
