### ISSUE TITLE
The directory name should not have trailing spaces.

### ISSUE THREAD

**Issue by pawliczka** [farmerbriantee/AgOpenGPS#282]
https://github.com/farmerbriantee/AgOpenGPS/blob/0d7e85e694d0ea4c8f2ec1d9f349bda9f1520ec6/SourceCode/GPS/Forms/FormFieldDir.cs#L68
Hello. Please remove trailing space. It is not needed and causes the folder existing check to fail when cboxAddDate.Checked and cboxAddTime.Checked is false. 

`mf.currentFieldDirectory = tboxFieldName.Text.Trim();`

**Comment by lansalot** [comment]
Removed in 5.7
