### ISSUE TITLE
FeatureRequest: Change workingdirectory of AGIO

### ISSUE THREAD

**Issue by hagre** [farmerbriantee/AgOpenGPS#302]
It would be very nice to make it possible to adjust the working directory (saving settings) corresponding to a moved working directory of AgOpenGPS.

**Comment by farmerbriantee** [comment]
But you can change the working directory to anything you wish.

**Comment by richardklasens** [comment]
The working directory is for AgIO is already in the AgOpenGPS folder in the windows documents folder.
