### ISSUE TITLE
Saving a field with the function 'Save As' gives an error when confirming

### ISSUE THREAD

**Issue by chrisriteco** [farmerbriantee/AgOpenGPS#306]
Saving a field with the function 'Save As' gives an error when confirming in the latest Git version. Exception in FormSaveAs.cs on Line 125. (Is one space too many in the path), this is added on line 68, but goes wrong. The strange thing is that this problem is not in the 5.7.2 release and nothing has been changed in the file.

**Comment by mirh** [comment]
The last git version has only one extra commit compared to 5.7.2 (unless you are talking about some of the alternative branches). 
And that's just a pretty dumb readme adjustment. 

Are you sure the problem couldn't be with whatever dev environment you have?

**Comment by richardklasens** [comment]
We tried this in the release but I can’t recreate the issue here

**Comment by chrisriteco** [comment]
Master branch checked out again and can't reproduce the problem.
