### ISSUE TITLE
Add more nuance to NTRIP server errors

### ISSUE THREAD

**Issue by mirh** [farmerbriantee/AgOpenGPS#319]
For the better part of last week, my trusty rtk corrections server was down. 
And I do know how to do a ping test, but not everyone is that shrewd. 
It would be nice if the `Connection Problem", "Not Connecting To Caster"` error could be a bit more specific. For instance:

* no answer at all on the specified server/port combo (maybe coupled with a check about internet connectivity working at all?)
* invalid credentials (error 401)
* resource/mountpoint/path not found (error 404)
* trimble also [seems](https://receiverhelp.trimble.com/alloy-gnss/en-us/ioConfig.html#IBSS/NTR) to define more status codes (602 and 604?) but idk really
* [something else](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) you think may be relevant?
* I did once solve an issue with the same aforementioned server, where my account wasn't authorized to have multiple clients connected at once (connection error 10035, in u-center) but I'm unsure how much specific this couldn't be

p.s. I also don't think it makes the most of sense to still have this error popup when you disconnect GPS and you are using the simulator

**Comment by craisbeck** [comment]
I did a bunch of troubleshooting with a pesky RTK connection this past winter and I thin the problem with your request is the errors and responses are different for different networks.  A connection failure on one system could be called Authentication Error and on the next system no error is reported and the next system a sign on failure.  My understanding is that there isn't a great deal of consistency across casters.

From: mirh ***@***.***>
Sent: Wednesday, May 10, 2023 6:20 AM
To: farmerbriantee/AgOpenGPS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [farmerbriantee/AgOpenGPS] Add more nuance to NTRIP server errors (Issue #319)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


For the better part of last week, my trusty rtk corrections server was down.
And I do know how to do a ping test, but not everyone is that shrewd.
It would be nice if the Connection Problem", "Not Connecting To Caster" error could be a bit more specific. For instance:

  *   no answer at all on the specified server/port combo (maybe coupled with a check about internet connectivity working at all?)
  *   invalid credentials (error 401)
  *   resource/mountpoint/path not found (error 404)
  *   trimble also seems<https://receiverhelp.trimble.com/alloy-gnss/en-us/ioConfig.html#IBSS/NTR> to define more status codes (602 and 604?) but idk really
  *   something else<https://en.wikipedia.org/wiki/List_of_HTTP_status_codes> you think may be relevant?
  *   I did once solve an issue with the same aforementioned server, where my account wasn't authorized to have multiple clients connected at once (connection error 10035, in u-center) but I'm unsure how much specific this couldn't be

p.s. I also don't think it makes the most of sense to still have this error popup when you disconnect GPS and you are using the simulator

-

**Comment by craisbeck** [comment]
Code it up.  It sounds promising.

**Comment by lansalot** [comment]
> I mean, I ***really*** don't think there's any way you can go wrong with HTTP error messages (I suppose there's the small dilemma of choosing whatever you want a SYN or ACK tcping, but it doesn't seem that fundamental)


I think your mistake is to assume all casters use standard http responses. And they just don't. I looked about 5 or 6 in regard to this some time back, and they were all over the place.

**Comment by mirh** [comment]
Even just for the most stupid "incorrect login" or "wrong mountpoint" scenarios? Jeez. 
Well, at the most horrific possible worst you could just have a whitelist/lookup table for each different server software I guess..
(and no, I wished I had the time to code all of this, on top of barely being able to make comprehensive enough reports)

Though at the most simplest end instead, a timid start could just be separating the "everything is dead silent" case from the "any other problem" one.

**Comment by MrPoke21** [comment]
![kép](https://github.com/farmerbriantee/AgOpenGPS/assets/16113422/69774c94-8167-4230-95ac-ff5efc1781ac)

**Comment by mirh** [comment]
That's some nice start, but an error/message box could be appropriate if you are in *FormNtrip* trying to do the first setup. 
I certainly wouldn't block the whole screen just because the server was down.

**Comment by mirh** [comment]
This wasn't fixed, and not even the promising #348 was merged.
