### ISSUE TITLE
IMU Orientation isn't available in Steer Wizard

### ISSUE THREAD

**Issue by gunicsba** [farmerbriantee/AgOpenGPS#324]
X / Y selector not visible in steer wizard.

**Comment by mirh** [comment]
Was #311 too disorganized/scattered?

**Comment by gunicsba** [comment]
@mirh  I believe in the 1 issue 1 ticket 1 commit to fix.

**Comment by mirh** [comment]
Totally fair, for as much as I was also concerned with not opening too many lowbrow questions.

**Comment by mirh** [comment]
This wasn't fixed. 
Only the gods know why a mass closure event was needed, as if some complete total rewrite (like QtAgOpenGPS) had happened.
