### ISSUE TITLE
Option 'Dual As IMU' is in the wrong tab in the configuration.

### ISSUE THREAD

**Issue by chrisriteco** [farmerbriantee/AgOpenGPS#326]
Something went wrong with the control panel. 

- The 'Dual As Imu' option is **not** available if you chose 'Fix'. 
- The 'Dual As Imu' option is now only available if you choose 'Dual', but then AG will continue to drive on the heading of the Dual and will **not** switch to Fix2Fix and use the Dual as IMU.

**Comment by richardklasens** [comment]
Function is removed
