### ISSUE TITLE
Tool Offset - A-B Line

### ISSUE THREAD

**Issue by aortner** [farmerbriantee/AgOpenGPS#34]
When using tool offset bigger then the half off tool widht ag jumps from a a-b line to another
eg 600 cm tool 310 cm offset

![image](https://user-images.githubusercontent.com/23136635/39539840-2425d8d2-4e41-11e8-98db-5d3923341c66.png)

**Comment by farmerbriantee** [comment]
i can't fix it :( 

It needs some offset.
