### ISSUE TITLE
AgIO GUI displays incorrect LAT and LON Data

### ISSUE THREAD

**Issue by chriskinal** [farmerbriantee/AgOpenGPS#340]
The OGI box on the System Data screen shows the correct LAT / LON data of the PAOGI sentence. However, the display of this data in upper left corner of the System Data screen and the main AgIO screen is wrong. The whole degrees are right but everything after the decimal point is wrong. It appears the correct data is sent to the AOG application as the "tractor" is in the right location. 
![AgIO_5 7](https://github.com/farmerbriantee/AgOpenGPS/assets/118364224/92cdfff6-a0c1-48f2-a68b-2851088f940b)

**Comment by lansalot** [comment]
I think those are the raw, uncooked values. In the AOG code, you'll find the calculations used to convert them.

**Comment by chriskinal** [comment]
Not sure what is meant by "raw, uncooked" values. The OGI box contains the correct GPS coordinates multiplied by 100 to move the decimal point two places right. The AgIO GUI seems to multiply them by 100 but butchers everything after the decimal point.

I believe the LAT display should show 32.3542691 not 32.5904485.

**Comment by lansalot** [comment]
Found the code, it's here:
https://github.com/farmerbriantee/AgOpenGPS/blob/master/SourceCode/AgIO/Source/Forms/NMEA.Designer.cs

ParsePANDA and ParsePAOGI methods. It explains it there - it's the conversion from Degrees to Decimal Degrees I think.

![image](https://github.com/farmerbriantee/AgOpenGPS/assets/9885921/b86b36b4-2090-43e3-a9ce-81c1b7d4b71e)

![image](https://github.com/farmerbriantee/AgOpenGPS/assets/9885921/dd631c39-d828-41e8-a2bb-f61053ce987d)

**Comment by chriskinal** [comment]
Got it.

**Comment by chriskinal** [comment]
After seeing the conversion code the values are correct.

**Comment by mirh** [comment]
One could also argue it's a bit disturbing to have different latitude and longitude string orders depending on the screen you open.
