### ISSUE TITLE
loading Vehicle

### ISSUE THREAD

**Issue by mtz8302** [farmerbriantee/AgOpenGPS#35]
I saved a Vehicle and couldn't load it on the other computer. Maybe bug in export or import of vehicles?
[Vehicle.zip](https://github.com/farmerbriantee/AgOpenGPS/files/1998761/Vehicle.zip)

combine forum post 1949 page 195

problem only with comma using countrys, set to English it works
Bugfix acutally: if version >9 Version *= version * 0.1
not realy fixed

**Comment by farmerbriantee** [comment]
Is this still an issue?

**Comment by mtz8302** [comment]
should be working up to version 9;-)
