### ISSUE TITLE
Section Control: turning on sections moving backwards

### ISSUE THREAD

**Issue by mtz8302** [farmerbriantee/AgOpenGPS#36]
I think I found a bug in AOG:
I’m using a small tractor for spraying and a 15m rigid sprayer. I do 15m headland first, so the sprayer knows when to stop.
When I’m driving from the headland into the line, the outer 2 sections go backwards, as the tractor could almost turn on a dime. At the begin of the turn these sections are close to the unapplied middle of the field. Now I turn and the start moving fast away (backwards) from the field but AOG turns them on. I think AOG thinks they are moving fast towards the unapplied and switch them on. I set 0,8 seconds look ahead. The problem might be that AOG doesn’t see the direction, the sections move, it only calculates distance to unapplied and speed and if it is smaller than look ahead time, turns them on.

I added some pics. The screenshoot are made with the simulator using the field from yesterday, so the vehicle is not at the exact wright position... . It should be a sequence, showing me driving a line out into headland and into the next line. The order is mixed up while uploading.. The one with the text explanations is the last.

combine forum post 1999 page 200
![section control 3](https://user-images.githubusercontent.com/35091324/40277503-39bf7f4e-5c20-11e8-882c-6e1914897b3f.jpg)
![section control 4](https://user-images.githubusercontent.com/35091324/40277504-39e225bc-5c20-11e8-8595-9f3086b93042.jpg)
![section control 5](https://user-images.githubusercontent.com/35091324/40277505-39fe86a8-5c20-11e8-9a20-222de7ba814a.jpg)
![section control 1](https://user-images.githubusercontent.com/35091324/40277506-3a1ab030-5c20-11e8-87c6-12ce64336117.jpg)
![section control 2](https://user-images.githubusercontent.com/35091324/40277507-3a58548a-5c20-11e8-9445-7cf7448846f9.jpg)

**Comment by farmerbriantee** [comment]
In a single headland you are moving forward and that triggers the section to turn on, its only for a very short time, but it catches it every time. Just going backwards, the section will turn off after the allotted turn off delay setting
