### ISSUE TITLE
Open field

### ISSUE THREAD

**Issue by aortner** [farmerbriantee/AgOpenGPS#38]
Case

Field is open and has a used area
I press start - field 

Ag ask me what do: cancel oder Save an der close Field
That’s ok
But after this new field dialog should come up 

Now I need to press start -field again

**Comment by farmerbriantee** [comment]
Well no, because there are activities like saving a vehicle etc that can only be done when all the fields are closed. The GUI needs to allow the user to do everything, you can't set it up to do only the most common activities.
