### ISSUE TITLE
IMU Position compensation

### ISSUE THREAD

**Issue by nemethdann** [farmerbriantee/AgOpenGPS#390]
Hello,

I think at _Position.designer.cs_ the IMU correction calculation is faulty.
`rollCorrectionDistance = Math.Tan(glm.toRadians((ahrs.imuRoll))) * -vehicle.antennaHeight;`
should be 
`rollCorrectionDistance = Math.Sin(glm.toRadians((ahrs.imuRoll))) * -vehicle.antennaHeight;`
at line 253.
We should shift the position in 2D, so we need the horizontal component of the antenna movement.

About the sign i'm not sure, if it's - or +vehicle.antennaHeight.

![imuCorrectionFault](https://github.com/farmerbriantee/AgOpenGPS/assets/167427998/ab90310b-0a68-4ca4-af67-710a4ddd4e8c)

**Comment by farmerbriantee** [comment]
Try taking the sin and the tangent of 5 degrees. You will see its the same thing anyway. Even at 15 degrees - its almost the same.

Could put sin - but it doesn't change anything.
