### ISSUE TITLE
tcp input

### ISSUE THREAD

**Issue by aortner** [farmerbriantee/AgOpenGPS#4]
Hi! if it possible could you integrate input from tcp for nmea signals?

i use  a reach rtk device and it outputs signals per tcp...

emlid.com/reach/

**Comment by farmerbriantee** [comment]
Hey wow great question. Have you been on Combine Forum? In the technology section there is some discussion regarding reach. Would you mind sharing your experience there? 

http://www.thecombineforum.com/forums/31-technology/279889-rtk-budget.html

I will look into tcp as an input. Its a whole new world for me, never did that before.

**Comment by aortner** [comment]
ok thank you.

i did write into the forum and like sharing my experience with others...
