### ISSUE TITLE
taking into account the adjustment of the lightbar for use without autoguidance, particularly on quad

### ISSUE THREAD

**Issue by Tervuren** [farmerbriantee/AgOpenGPS#400]

**Comment by Tervuren** [comment]
(https://github.com/Tervuren/AgOpenGps)

**Comment by richardklasens** [comment]
@Tervuren you need to only push the changes and not upload it the way you did now. It’s changing every file, and looses history. Please do as follow:

clone the repo using to your own GitHub page GitHub desktop
Make changes on your pc in your local repo
Push back to your GitHub repo
Make a pull request from your GitHub repo branch to the original GitHub here.
Even better is make a new branch first.
