### ISSUE TITLE
Window hidden because it appears out of screen

### ISSUE THREAD

**Issue by gunicsba** [farmerbriantee/AgOpenGPS#405]
There are ways to make the window go outside of the actual screen.
See video of bricbric: https://youtu.be/VL7Nh5VCQ70

Another easy to reproduce is when you use the tablet inhouse and put AOG on the external big screen. Take it to the tractor and it still starts on the external (currently not connected, not visible) screen.

@lansalot  did found a class that adress this:
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.screen?view=windowsdesktop-8.0&redirectedfrom=MSDN

**Comment by FarmerKevin** [comment]
I have experienced annoyance with the window shrinking, or moving if finger slides on screen (bouncing through field). Greatly helps if you steady hand with fingers on outside on tablet and use thumb to push. Trying to get others to do the same is the issue. Would b nice if it only changes with minimize, or buttons intended. Thanks! Keep up the great work!Kevin Alward On May 21, 2024 9:31 AM, gunicsba ***@***.***> wrote:
There are ways to make the window go outside of the actual screen.
See video of bricbric: https://youtu.be/VL7Nh5VCQ70
Another easy to reproduce is when you use the tablet inhouse and put AOG on the external big screen. Take it to the tractor and it still starts on the external (currently not connected, not visible) screen.
@lansalot  did found a class that adress this:
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.screen?view=windowsdesktop-8.0&redirectedfrom=MSDN

**Comment by farmerbriantee** [comment]
Resolved - puts any offscreen windows to 0,0
