### ISSUE TITLE
angle sensor

### ISSUE THREAD

**Issue by ogfdean** [farmerbriantee/AgOpenGPS#406]
Angle sensor has input and output but the system does not recognize it. not being tech savvy can i get a detailed description of how to solve this problem in plain language?

**Comment by Davidwedel** [comment]
Hello. There's a forum for questions, that a lot more people watch than this. 
https://discourse.agopengps.com/

You might get farther asking on there.

**Comment by ogfdean** [comment]
Thanks will review ag open gps more,  have tried their posted  solutions  to no avail. Getting to point that the provided board is faulty. Sent from Mail for Windows From: David WedelSent: Friday, May 24, 2024 6:47 AMTo: farmerbriantee/AgOpenGPSCc: ogfdean; AuthorSubject: Re: [farmerbriantee/AgOpenGPS] angle sensor (Issue #406) Hello. There's a forum for questions, that a lot more people watch than this.https://discourse.agopengps.com/You might get farther asking on there.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by farmerbriantee** [comment]
This is not an issue with the software, but with hardware

**Comment by ogfdean** [comment]
Still looking for solutions. With a repair technician
