### ISSUE TITLE
Boundary recording window always fullscreen when Windows is in tablet mode

### ISSUE THREAD

**Issue by vviitani** [farmerbriantee/AgOpenGPS#41]
When recording boundary, the window with record button always expands to full screen mode with no possibility to resize. This happens only if Windows is in tablet mode. 

Suggested solution: in FormBoundaryPlayer.cs change property FormBorderStyle to FixedSingle (currently Sizeable). It seems to fix the problem.

**Comment by farmerbriantee** [comment]
Next Update will have this. Thank you!
