### ISSUE TITLE
Speed indicator not working if there are no NMEA VTG message present 

### ISSUE THREAD

**Issue by Xyntexx** [farmerbriantee/AgOpenGPS#410]
The GPS needs to output VTG messages for speed measurements to work. If no VTG message is present the speed will show 3.4E+38. This issue could be fixed by calculating the speed from the position like the simulator does.

**Comment by Davidwedel** [comment]
VTG is also used for heading. It's an essential.

**Comment by farmerbriantee** [comment]
Yes, if using GGA, you also need to use VTG to get the speed. We tried manually calculating based on fix, but wasn't stable. Just enable vtg to be sent in your gps
