### ISSUE TITLE
AgOpenGPS brazil

### ISSUE THREAD

**Issue by Rtguirao** [farmerbriantee/AgOpenGPS#411]
Developers can add the Portuguese language (Brazil), to make it easier for Brazilian users

**Comment by farmerbriantee** [comment]
Portugese added to v6.3.3

**Comment by Rtguirao** [comment]
Thanks
I believe it will make it much easier, I will be updating my project
Thank you very much for your attention and agility, I am grateful to be able to contribute

________________________________
De: Brian Tischler ***@***.***>
Enviado: sábado, 13 de julho de 2024 17:53
Para: farmerbriantee/AgOpenGPS ***@***.***>
Cc: Rtguirao ***@***.***>; Author ***@***.***>
Assunto: Re: [farmerbriantee/AgOpenGPS] AgOpenGPS brazil (Issue #411)


Portugese added to v6.3.3
