### ISSUE TITLE
When saving a CurveLine it looks like the error text is wrong.

### ISSUE THREAD

**Issue by dairytech** [farmerbriantee/AgOpenGPS#46]
In the code below from SaveOpen.Designer.cs it looks like maybe the text, "Saving AB Line" should be "Saving CurveLine".  See the text near the bottom below and/or line 1549 in Visual Studio.  If this was my code I would say that I cut and paste the previous block and forgot to edit this text. :)

        //save all the flag markers
        public void FileSaveCurveLine()
        {
            //Saturday, February 11, 2017  -->  7:26:52 AM

            //get the directory and make sure it exists, create if not
            string dirField = fieldsDirectory + currentFieldDirectory + "\\";

            string directoryName = Path.GetDirectoryName(dirField);
            if ((directoryName.Length > 0) && (!Directory.Exists(directoryName)))
            { Directory.CreateDirectory(directoryName); }

            //use Streamwriter to create and overwrite existing ABLine file
            using (StreamWriter writer = new StreamWriter(dirField + "CurveLine.txt"))
            {
                try
                {
                    //write out the ABLine
                    writer.WriteLine("$CurveLine");

                    //write out the aveheading
                    writer.WriteLine(curve.aveLineHeading.ToString(CultureInfo.InvariantCulture));

                    //write out the points of ref line
                    writer.WriteLine(curve.refList.Count.ToString(CultureInfo.InvariantCulture));
                    if (curve.refList.Count > 0)
                    {
                        for (int j = 0; j < curve.refList.Count; j++)
                            writer.WriteLine(curve.refList[j].easting.ToString(CultureInfo.InvariantCulture) + "," +
                                                curve.refList[j].northing.ToString(CultureInfo.InvariantCulture) + "," +
                                                    curve.refList[j].heading.ToString(CultureInfo.InvariantCulture));
                    }
                }

                catch (Exception e)
                {
                    Console.WriteLine(e.Message + "\n Cannot write to file.");
                    WriteErrorLog("Saving AB Line" + e.ToString());

                    return;
                }

            }
        }

**Comment by farmerbriantee** [comment]
Good catch, its called refactoring! And stuff always gets missed lol.
