### ISSUE TITLE
Headland Function not implemented

### ISSUE THREAD

**Issue by youngfarmer365** [farmerbriantee/AgOpenGPS#53]
I'm still in simulator but can not get headland mode to work. I keep getting the attached message.
![agopengps](https://user-images.githubusercontent.com/47012940/51711423-fe114680-2023-11e9-8204-2ea5afaf781a.png)

Is it just me? any help or clarification would be greatly appreciated!

**Comment by Farmer123456** [comment]
I have the same Problem!

**Comment by farmerbriantee** [comment]
Well its not a problem, its telling you that they aren't implemented.
