### ISSUE TITLE
relay 

### ISSUE THREAD

**Issue by efremidiskon** [farmerbriantee/AgOpenGPS#62]
follow the tutorial video om youtube but relays didnt work. why?

**Comment by ArBe-AU** [comment]
This would be better asked on the AgOpenGPS thread on the Combine Forum - the url is https://www.thecombineforum.com/forums/31-technology/278810-agopengps.html

**Comment by farmerbriantee** [comment]
We are going to remove all the rate stuff and have section control on the relay port. It will work a lot better and simpler.
