### ISSUE TITLE
SIM 868 GPS/GSM module serial connection

### ISSUE THREAD

**Issue by vanvince** [farmerbriantee/AgOpenGPS#82]
Hi, 

I'm trying to connect a GPS/GSM module to AgOpenGPS through one of my laptop USB port. The module is SIM868 GSM/GPS/GNSS hat by Waveshare. 
If I use this device with a simple puTTY serial connection it works perfectly fine and eventually gets GPS FIX on the other hand when I connect it to AgOpenGPS by clicking on "PORTS" and put the correct COM port, baud-rate and NMEA rate (1Hz) there is NO CONNECTION. I can read only the "Initial settings" message inside the text box.
Does anyone know how to solve this issue? Is it possible to connect this kind of module to AgOpenGPS? 

Thank you in advance.

**Comment by richardklasens** [comment]
Does the receiver output nmea data?

Met vriendelijke groet,
 
Richard Klasens

**Comment by vanvince** [comment]
@richardklasens yeah of course. 
Normally I send to this module an AT command and receive a response over the serial port. To obtain NMEA data I send this command sequence: 
AT+CGNSPWR=1 (to power on the GNSS module)
AT+CGNSTST=1 (to start receiving NMEA data) 
from now on it continues to send NMEA data through the serial port.

**Comment by farmerbriantee** [comment]
Is it sending a GPGGA sentence? Can you take a screen shot of the Serial Ports form, what is in the box that shows the gps sentence?

**Comment by farmerbriantee** [comment]
BTW 1 Hz is not much use other then to just show where you are, minumum 5 Hz required

**Comment by vanvince** [comment]
@farmerbriantee  1Hz is module basic setting. 
Here there is an example of messages from and to module (I'm in my office so there is no GPS fix).
![Annotazione 2019-10-07 102124](https://user-images.githubusercontent.com/40863611/66296756-8c95d180-e8ee-11e9-9bdc-d64ca206b808.png)
As we can see in the picture above the module gives a GNgga sentence and not GPgga. Maybe this is my issue. 
What can I do? Is there any way to change GNGGA to GPGGA? 

By the way, I have an ardusimple RTK module too. Can I use it? Are there any particular settings to do so?

best regards, 
Vincenzo Cristiano

**Comment by aortner** [comment]
you should no use that module if you have a rtk from ardusimple.
just use ucenter to setup the module.

**Comment by vanvince** [comment]
@aortner yeah I know but I wanted to test this module too. Anyway, ardusimple RTK works fine and it was extremely easy to use with AgOpenGPS

**Comment by farmerbriantee** [comment]
AgOpenGPS will decode both GNGGA and GPGGA so that should not be a problem.

**Comment by farmerbriantee** [comment]
please post your question in the forum... [https://agopengps.discourse.group/c/gps-rtk-gnss](url)
