### ISSUE TITLE
section width in emperial  units

### ISSUE THREAD

**Issue by kansasfarmer** [farmerbriantee/AgOpenGPS#9]
when using imperial units .  8 rows 30 inch rows so i put 30 in all sections  save .  go back to settings and it is now 99 on 7 sections and 1555 on 1 . thanks for starting this its just what im looking for i need some advice on how to get enough programing knowledge to help on this project. thanks

**Comment by farmerbriantee** [comment]
Goodness, this is old, sorry i rarely come here for comments. You just have to start programming, i learned C# over the past year and this project was a good way to do it. There is lots of books and especially lots of you tube videos and websites. I fixed that section issue.

The main discussion happens here: http://www.thecombineforum.com/forums/31-technology/278810-agopengps.html

Lotsof really good info there
