### ISSUE TITLE
Upgrade target framework to .net 4.6.2

### ISSUE THREAD

**Issue by buttontate** [farmerbriantee/AgOpenGPS#98]
What are your thoughts on upgrading the solution to target 4.6.2. This is the default framework that ships with windows 10. I believe this would be a pretty painless upgrade. Also adds some support and vulnerability patches.

**Comment by farmerbriantee** [comment]
It limits those with older VStudio versions, 4.5 is only needed. PAtches are also applied to older versions like 4.5

**Comment by buttontate** [comment]
Thats true. the newest Visual Studio Community is free to use but I see your point.
