### ISSUE TITLE
Use Nuget for dependent packages.

### ISSUE THREAD

**Issue by buttontate** [farmerbriantee/AgOpenGPS#99]
Looks like there are some dependences hard referenced in the solution. I was able to use Nuget for almost all of them. This would enable upgrading package references easily when they are released.

**Comment by farmerbriantee** [comment]
This project is for people learning and just starting out. Trying to keep things as simple as possible, hope this makes sense

**Comment by farmerbriantee** [comment]
I guess its should vs could.

**Comment by buttontate** [comment]
I see your point and I'm just suggesting things to make things easier. 

Nuget package source is included by default in visual studio so it's no additional setup. The majority of .net examples on the web reference packages so they don't have to include the references in the repo or if its an article they don't have to host the actual references to download.

Just a thought.
